attempt to fix this
2016-04-26 16:07:49,566 - t.140695781648192 - DEBUG - ln.232 - submission_page_url: 'https://www.weasyl.com/submission/10370'
Fetch https://www.weasyl.com/submission/10370 ...2016-04-26 16:07:49,567 - t.140695781648192 - INFO - ln.716 - Starting new HTTPS connection (1): www.weasyl.com
2016-04-26 16:07:49,638 - t.140695781648192 - DEBUG - ln.395 - Setting read timeout to 60
2016-04-26 16:07:50,061 - t.140695781648192 - DEBUG - ln.435 - "GET /submission/10370 HTTP/1.1" 200 None
200
Fetch https://cdn.weasyl.com/~pikuna/submissions/10370/91fd9a8cf68d38f0ec75eb1ad84984073861f905beef5906b84e65546b039d27/pikuna-working.png?download ...2016-04-26 16:07:50,948 - t.140695781648192 - INFO - ln.716 - Starting new HTTPS connection (1): cdn.weasyl.com
2016-04-26 16:08:30,989 - t.140695781648192 - CRITICAL - ln.374 - Unhandled exception!
2016-04-26 16:08:30,990 - t.140695781648192 - ERROR - ln.375 - HTTPSConnectionPool(host='cdn.weasyl.com', port=443): Max retries exceeded with url: /~pikuna/submissions/10370/91fd9a8cf68d38f0ec75eb1ad84984073861f905beef5906b84e65546b039d27/pikuna-working.png?download (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)
Traceback (most recent call last):
  File "submission.py", line 372, in main
    cli()
  File "submission.py", line 342, in cli
    stop_number = args.end_num
  File "submission.py", line 312, in save_submission_range
    success = save_submission(output_path,submission_number)
  File "submission.py", line 285, in save_submission
    submission_page_html
  File "submission.py", line 185, in save_submission_normal
    submission_media = get_url_requests(submission_media_link)
  File "/home/ctrls/weasyl_siterip/utils.py", line 225, in get_url_requests
    response = fetch(url, method='get', data=None, expect_status=200, headers=None)
  File "/home/ctrls/weasyl_siterip/utils.py", line 196, in fetch
    response = requests.get(url, headers=headers, timeout=60)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='cdn.weasyl.com', port=443): Max retries exceeded with url: /~pikuna/submissions/10370/91fd9a8cf68d38f0ec75eb1ad84984073861f905beef5906b84e65546b039d27/pikuna-working.png?download (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)